stages:
  - test
  - update_build_version
  - build
#  - test_deployment
#  - alpha_deployment
#  - beta_deployment
#  - production_deployment

.android_key_store:
  before_script:
    - echo "$PLAY_STORE_UPLOAD_KEY" | base64 --decode > /builds/elevemoi/mobile/android/key.jks
    - echo "storePassword=$KEYSTORE_PASSWORD" >> android/signing.properties
    - echo "keyPassword=$KEY_PASSWORD" >> android/signing.properties
    - echo "keyAlias=$KEY_ALIAS" >> android/signing.properties
    - echo "storeFile=/builds/elevemoi/mobile/android/key.jks" >> android/signing.properties

.setup_fastlane_android:
  extends: .android_key_store
  variables:
    LC_ALL: "en_US.UTF-8"
    LANG: "en_US.UTF-8"
  before_script:
    - cd android/
    - gem install bundler
    - bundle install
    - echo "$KEY_FIREBASE_APP_DISTRIBUTION" >> /builds/elevemoi/mobile/android/KEY_FIREBASE_APP_DISTRIBUTION.json

test:
  image: cirrusci/flutter:stable
  stage: test
  script:
    - flutter test

update_build_version:
  stage: update_build_version
  image:
    name: mohamnag/ubuntu-git
    entrypoint: [""]
  script:
    - sh scripts/update_version.sh update_build_version
    - sh scripts/update_version.sh commit_push_and_tag

build_android_before_release:
  image: cirrusci/flutter:stable
  stage: build
  extends: .android_key_store
  script:
    - VERSION=$(sh update_version.sh get_version)
    - BUILD_VERSION=$(sh update_version.sh get_build_version)
    - flutter pub get
    - flutter build appbundle --build-number=$BUILD_VERSION --build-name=$VERSION
  artifacts:
    paths:
      - build/app/outputs/bundle/release/app-release.aab
      - build/app/outputs/apk/release/app-release.apk
    expire_in: 1 day
  dependencies:
    - update_build_version

#build_android:
#  stage: build
#  extends: .android_key_store
#  script:
#    - flutter pub get
#    - flutter packages pub run flutter_launcher_icons:main
#    - flutter build apk
#  artifacts:
#    paths:
#      - build/app/outputs/apk
#  except:
#    - main
#    - develop
#
#android_play_store_internal_deployment:
#  stage: test_deployment
#  extends: .setup_fastlane_android
#  dependencies:
#    - build_android_before_release
#  script:
#    - bundle exec fastlane upload_to_play_store_internal
#    - bundle exec fastlane upload_to_firebase
#  only:
#    - develop
#
#android_play_store_alpha_deployment:
#  stage: alpha_deployment
#  extends: .setup_fastlane_android
#  dependencies:
#    - android_play_store_internal_deployment
#  script:
#    - bundle exec fastlane promote_internal_to_alpha
#  when: manual
#  only:
#    - develop
#
#android_play_store_beta_deployment:
#  stage: beta_deployment
#  extends: .setup_fastlane_android
#  dependencies:
#    - build_android
#  script:
#    - bundle exec fastlane promote_alpha_to_beta
#  allow_failure: false
#  when: manual
#  only:
#    - main
#
#android_play_store_productive_deployment:
#  stage: production_deployment
#  extends: .setup_fastlane_android
#  dependencies:
#    - android_play_store_beta_deployment
#  script: bundle exec fastlane promote_alpha_to_production
#  allow_failure: false
#  when: manual
#  only:
#    - main
