stages:
  - test
  - update_build_version
  - build
  - deploy

.android_key_store:
  before_script:
    - echo "$PLAY_STORE_UPLOAD_KEY" | base64 --decode > /builds/elevemoi/mobile/android/key.jks
    - echo "storePassword=$KEYSTORE_PASSWORD" >> android/signing.properties
    - echo "keyPassword=$KEY_PASSWORD" >> android/signing.properties
    - echo "keyAlias=$KEY_ALIAS" >> android/signing.properties
    - echo "storeFile=/builds/elevemoi/mobile/android/key.jks" >> android/signing.properties

.setup_fastlane_android:
  extends: .android_key_store
  variables:
    LC_ALL: "en_US.UTF-8"
    LANG: "en_US.UTF-8"
  before_script:
    - cd android/
    - gem install bundler
    - bundle install
    - echo "$KEY_FIREBASE_APP_DISTRIBUTION" >> /builds/elevemoi/mobile/android/KEY_FIREBASE_APP_DISTRIBUTION.json

test:
  image: cirrusci/flutter:stable
  stage: test
  script:
    - flutter test

update_build_version:
  stage: update_build_version
  image:
    name: mohamnag/ubuntu-git
    entrypoint: [""]
  script:
    - sh scripts/update_version.sh update_build_version
    - sh scripts/update_version.sh commit_push_and_tag

build:
  image: cirrusci/flutter:stable
  stage: build
  script:
    - VERSION=$(sh scripts/update_version.sh get_version)
    - BUILD_VERSION=$(sh scripts/update_version.sh get_build_version)
    - flutter pub get
    - flutter build appbundle --build-number=$BUILD_VERSION --build-name=$VERSION
  artifacts:
    paths:
      - build/app/outputs/bundle/release/app-release.aab
    expire_in: 1 day

deploy:
  image: ruby:2.7
  stage: deploy
  extends: .setup_fastlane_android
  script:
    - bundle exec fastlane deploy
