update_fastlane

default_platform(:android)

platform :android do
    desc "Deploy to firebase app distribution"
    lane :deploy do
        firebase_app_distribution(
            app: "1:820084350095:android:f23848926ef19789bda4fa",
            service_credentials_file: '../app/google-services.json',
            testers: "",
            release_notes: "News !",
            firebase_cli_path: "/usr/local/bin/firebase",
            android_artifact_type: 'aab',
            android_artifact_path: "../build/app/outputs/bundle/release/app-release.aab"
        )
    end
end